### ISSUE TITLE
 it's not playing. Key mark does not appear at the top of the agent

### ISSUE THREAD

**Issue by imadige** [Anton2319/WireGuardExamples#1]
it's not playing. Key mark does not appear at the top of the agent

**Comment by Anton2319** [comment]
Can you elaborate on your issue? By the way, it's possible that you need to tap the button two times on the first run

**Comment by imadige** [comment]
I tried it on android 10 and 11 phones. The first time I press it, a warning appears at the bottom, a lock sign will appear on the phone. but that lock image is not coming out at all. VPN status does not appear to be active. phones android 11 samsung, android 10 mi

**Comment by Anton2319** [comment]
Can you show me the logs from logcat? I will try to investigate

**Comment by vishaliosexpert** [comment]
**com.wireguard.config.BadConfigException: com.wireguard.crypto.KeyFormatException**
	at com.wireguard.config.Interface$Builder.parsePrivateKey(Interface.java:398)
	**at com.example.anton2319sdocsonwg.MainActivity$1.run(MainActivity.java:61)**
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.wireguard.crypto.KeyFormatException
	at com.wireguard.crypto.Key.fromBase64(Key.java:95)
	at com.wireguard.config.Interface$Builder.parsePrivateKey(Interface.java:396)
	... 5 more

**Comment by Anton2319** [comment]
> **com.wireguard.config.BadConfigException: com.wireguard.crypto.KeyFormatException**
> 	at com.wireguard.config.Interface$Builder.parsePrivateKey(Interface.java:398)
> 	**at com.example.anton2319sdocsonwg.MainActivity$1.run(MainActivity.java:61)**
> 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 	at java.lang.Thread.run(Thread.java:923)
> Caused by: com.wireguard.crypto.KeyFormatException
> 	at com.wireguard.crypto.Key.fromBase64(Key.java:95)
> 	at com.wireguard.config.Interface$Builder.parsePrivateKey(Interface.java:396)
> 	... 5 more

If you look to the top of the stacktrace you could see BadConfigException, that means you configured your keys incorrectly. Can you show me your wireguard config?

**Comment by vishaliosexpert** [comment]
thanks for replay.
use same file (DataSource.java )
private static final String JSON_STRING = "{\"user_info\":{\"username\":\"redacted\",\"password\":\"redacted\",\"vpn-name\":\"redacted\",\"PrivateKey\":\"base64=\",\"Address\":\"10.0.0.2/24\",\"DNS\":\"8.8.8.8\",\"PublicKey\":\"redacted=\",\"AllowedIPs\":\"0.0.0.0/1, 128.0.0.0/1, ::/1, 8000::/1\",\"Endpoint\":\"redacted:51820\",\"status\":\"Active\",\"vpnConnection\":true},\"server_info\":{\"url\":\"10.0.0.1\"}}";

**Comment by Anton2319** [comment]
> thanks for replay.
> use same file (DataSource.java )
> private static final String JSON_STRING = "{\"user_info\":{\"username\":\"redacted\",\"password\":\"redacted\",\"vpn-name\":\"redacted\",\"PrivateKey\":\"base64=\",\"Address\":\"10.0.0.2/24\",\"DNS\":\"8.8.8.8\",\"PublicKey\":\"redacted=\",\"AllowedIPs\":\"0.0.0.0/1, 128.0.0.0/1, ::/1, 8000::/1\",\"Endpoint\":\"redacted:51820\",\"status\":\"Active\",\"vpnConnection\":true},\"server_info\":{\"url\":\"10.0.0.1\"}}";

This is the example config, you need to replace these values to match the values of your server. On how to configure wireguard you can refer here: https://www.wireguard.com/quickstart/

**Comment by vishaliosexpert** [comment]
thanks, it's working.
